import mn from './mn.mjs';
export const company = {name:'Ashid Apex Consulting LLC',email:'Ashidapex.consulting@gmail.com',phone:'77777777',tel:'+97677777777',url:'https://aac.mn'};
export const slugs=['home','about','services','industries','employers','partners','process','faq','jobs','contact','privacy','terms'];
export const content={
en:{
nav:['Home','About us','Services','Industries','For employers','International partners','Our process','FAQ & compliance','Careers','Contact','Privacy','Website terms'],
tag:'INTERNATIONAL RECRUITMENT · MONGOLIA',hero:'The right people.\nA stronger future.',intro:'Your trusted partner for foreign workforce in Mongolia. Connecting Mongolian employers with qualified international workers and reliable recruitment agencies.',request:'Request workers',partner:'Become a partner',learn:'Explore our approach',all:'Explore all services',eyebrow:'PEOPLE. POSSIBILITY. PROGRESS.',
homeIntro:'International reach.\nLocal understanding.',homeBody:'From understanding your workforce needs to arrival and follow-up, we bring structure and clarity to international recruitment. One coordinated process, built around your business.',
pillars:[['Local understanding','Recruitment shaped by the needs of employers in Mongolia.'],['Connected expertise','Collaboration with overseas recruitment agencies and candidates.'],['Clarity at every step','Defined requirements, transparent communication and coordinated delivery.']],
serviceTitle:'Workforce solutions,\nfrom start to settle.',serviceIntro:'A coordinated journey from the first requirement to the first day at work—and beyond.',
services:[['Workforce recruitment','We define your requirements, source suitable candidates and coordinate recruitment with overseas partners.','Role profiles · Workforce planning · Candidate sourcing'],['Candidate screening','CV review, experience verification, skills assessment and interview coordination help employers make informed decisions.','CV review · Skills assessment · Interviews'],['Documentation support','We coordinate employment and immigration-related documents according to the requirements of each assignment.','Document checklists · Employer coordination · Application support'],['Arrival & placement','Travel and arrival coordination connect selected workers with the hiring employer and their workplace.','Arrival planning · Workplace handover · Onboarding coordination'],['Post-placement follow-up','We maintain communication with employers and workers to support the transition into the workplace.','Employer check-ins · Worker communication · Issue coordination']],
industryTitle:'People for the industries\nthat move Mongolia.',industryIntro:'Skilled and semi-skilled recruitment aligned with your operational needs. Roles below illustrate the workforce categories we can discuss, not advertised vacancies.',
industries:[['Construction & civil works','Welders, electricians, plumbers, carpenters, steel fixers and masons.'],['Manufacturing & production','Production workers, assembly staff and technical roles.'],['Mining','Heavy equipment operators, maintenance and supporting trades.'],['Agriculture & farming','Farm workers and seasonal production support.'],['Solar energy & installation','Installation teams, electricians and technical support.'],['Automotive service','Automotive technicians and workshop support.'],['Logistics & warehousing','Warehouse workers and logistics support teams.']],
processTitle:'A clear path,\nfrom need to placement.',processIntro:'Seven connected stages. Clear responsibilities. Communication throughout.',
steps:[['Define the requirement','Share positions, headcount, skills, working conditions and your target start date.'],['Source candidates','We coordinate with overseas recruitment partners to identify suitable people.'],['Screen & interview','Review experience, assess skills and meet shortlisted candidates.'],['Employer selection','The hiring employer selects candidates who meet the agreed requirements.'],['Coordinate documentation','We support the relevant employment, visa and permit documentation process.'],['Arrival & placement','Coordinate travel, arrival and the handover to your workplace.'],['Follow up','Continue communication with the employer and workers after placement.']],
aboutTitle:'Built on connection.\nFocused on your workforce.',aboutIntro:'Ashid Apex Consulting LLC is a Mongolia-based recruitment and workforce solutions company connecting employer demand with suitable recruitment partners and candidates overseas.',mission:'Our mission',missionText:'To make international workforce recruitment in Mongolia more structured, transparent and reliable.',vision:'Our vision',visionText:'To become a trusted bridge between Mongolian employers and international workforce markets.',valuesTitle:'The way we work',values:[['Understand first','A good placement starts with a clear understanding of the role and the workplace.'],['Communicate openly','We value clear expectations and timely information for all parties.'],['Build for the long term','We aim for lasting B2B relationships and continued support after placement.']],
employerTitle:'Build the workforce\nyour business needs.',employerIntro:'Tell us what you need. We will coordinate with our recruitment network to identify candidates who match your roles and workplace requirements.',employerChecklist:['Define the role, skills and experience.','Set out salary, benefits and working hours.','Confirm location, accommodation and contract period.','Share headcount and the target start date.'],prepare:'Before we begin',formTitle:'Tell us about your workforce needs',
partnerTitle:'Global connections.\nShared standards.',partnerIntro:'We welcome long-term B2B relationships with licensed, reliable overseas recruitment agencies providing qualified skilled and semi-skilled workers for Mongolia.',partnerChecklist:['Valid recruitment or manpower licence','Verified candidate database and relevant workforce categories','Transparent fees, processes and communication','Documentation capability and long-term cooperation'],partnerForm:'Introduce your agency',partnerNote:'Initial introductions are reviewed before a partnership is agreed. Please send company profiles and licence documents only when our team requests them.',
faqTitle:'Clarity before\nyou take the next step.',faqIntro:'Practical answers for employers and recruitment partners.',faq:[['What types of workers can you recruit?','We work with skilled and semi-skilled categories according to employer requirements. Share the roles, skills and experience you need so we can discuss suitability.'],['How long does recruitment take?','Timing depends on the position, candidate availability, documentation and applicable requirements. A proposed timeline is discussed after reviewing the requirement.'],['Who selects the workers?','The hiring employer makes the final selection following candidate screening and interviews.'],['Do you work with overseas agencies?','Yes. We are building long-term B2B relationships with qualified overseas recruitment partners.'],['Does documentation support guarantee a visa or work permit?','No. Documentation support is coordination assistance. Decisions remain with the relevant authorities, and requirements must be checked for each case.'],['How are fees and employment conditions agreed?','Service scope, fees, responsibilities and employment conditions should be clarified in writing before proceeding. Contact us to discuss your specific requirement.'],['How do I request workers?','Complete the employer request form, then review and send the prepared email to our team. You can also call or email us directly.']],compliance:'A responsible recruitment approach',complianceText:'Clear role requirements, transparent employment conditions and appropriate documentation are central to our approach. Our website does not replace case-specific advice or official decisions. Refer to the relevant authorities for current immigration and employment requirements.',
contactTitle:'Your next chapter\nstarts with a conversation.',contactIntro:'Whether you are hiring in Mongolia or seeking a reliable recruitment partner, let’s discuss how we can work together.',emailLabel:'EMAIL OUR TEAM',callLabel:'CALL US',officeLabel:'OUR OFFICE',address:'Sambuu Street 18, 5th khoroo, Chingeltei District, Ulaanbaatar, Mongolia',generalForm:'Send an inquiry',
jobsTitle:'Your skills.\nNew possibilities.',jobsIntro:'Employment opportunities in Mongolia, with clear information about the role and its conditions.',jobsEmpty:'No vacancies are currently published.',jobsText:'Contact our team for information about future opportunities. Please do not send passport or identity documents in your initial inquiry.',jobAction:'Ask about opportunities',
ctaTitle:'Let’s build your\nnext great team.',ctaBody:'Start with a conversation about your workforce needs.',footerText:'Foreign workforce recruitment & workforce solutions in Mongolia.',navigation:'Explore',connect:'Connect',rights:'All rights reserved.',skip:'Skip to content',menu:'Menu',close:'Close menu',back:'Back to home',
fields:{company:'Company name',name:'Contact person',email:'Email',phone:'Phone / WhatsApp (include country code)',industry:'Industry',position:'Position / job title',count:'Number of workers',skills:'Required skills & experience',salary:'Salary & benefits',accommodation:'Accommodation',hours:'Working hours',contract:'Contract period',start:'Target start date',message:'Additional details',country:'Country of operation',license:'Recruitment licence / issuing authority',profile:'Company website or profile link',categories:'Available workforce categories',capacity:'Current candidate capacity',fees:'Recruitment fees / terms',timeline:'Recruitment timeline',subject:'Subject'},
choose:'Please select',optional:'Optional',consent:'I understand that this form prepares an email. I agree to share these details with Ashid Apex Consulting for a response to my inquiry.',formNotice:'Your details stay in this page until you choose to send them. Review your request, then open your email app to send it. No documents or payments are required here.',review:'Review request',send:'Open email app',copy:'Copy request',download:'Download request',edit:'Edit request',ready:'Your request is ready to review',notSent:'Not sent yet. Send the email from your email app, or copy the request and email it to',copied:'Copied. Paste it into your email.',copyFailed:'Copy is unavailable. Select the request text or download it instead.',required:'Fields marked * are required.',
privacyTitle:'Privacy & your inquiry',privacyIntro:'A clear explanation of how this website handles the details you choose to share.',privacy:[['On this website','Forms prepare a request in your browser. We do not store form entries on this website or use analytics or advertising cookies.'],['When you send an email','Your email application and email provider process your message. Ashid Apex Consulting receives the details you send to respond to your inquiry and discuss services.'],['Share only what is needed','Use business contact details where possible. Do not include passport numbers, identity documents, medical records or other sensitive information in an initial inquiry.'],['Questions and requests','Contact Ashidapex.consulting@gmail.com with questions about your information or a request to correct or delete information you have sent.'],['Hosting','GitHub Pages hosts this website. GitHub may process technical connection information under its own privacy statement.']],
termsTitle:'Website terms',termsIntro:'Information to help you use this website.',terms:[['General information','Website content describes our recruitment services. It is not an offer of employment, a placement guarantee or a binding service quotation.'],['Separate agreements','Recruitment scope, fees, responsibilities and employment conditions are agreed separately in writing. Sending an inquiry does not form a service contract.'],['Documentation and approvals','Requirements and official decisions depend on the circumstances of each assignment. Documentation assistance does not guarantee a visa, permit or approval.'],['Accuracy and contact','Please contact our team to confirm availability, timelines and the information relevant to your requirements.']],
meta:'Ashid Apex Consulting connects Mongolian employers with qualified international workers and recruitment partners across construction, mining, manufacturing and more.'
},
mn
};
